### ISSUE TITLE
Dockerize this app

### ISSUE THREAD

**Issue by anuveyatsu** [FCSCOpendata/frontend#1]
So that we can quickly build docker images and deploy them.

## Acceptance criteria

* [ ] I have a Dockerfile in the root dir of this repo

## Tasks

* [ ] Create Dockerfile based on this example - https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile
* [ ] Build a docker image locally and test it
