### ISSUE TITLE
[Bug] Orgs carousel is glitching when switching from EN to AR

### ISSUE THREAD

**Issue by demenech** [FCSCOpendata/frontend#108]
## Description
1. Go to the homepage, make sure the language is set to English
2. Go to Organizations
3. Slide the orgs carousel to the next page
4. Switch the language to Arabic
5. Results:
![image](https://user-images.githubusercontent.com/16550934/190630868-1571c37e-56e4-4fd0-baac-19f064667b3d.png)

## Acceptance Criteria
- [ ] The issue is fixed

## Tasks
- [ ] Investigate the issue
- [ ] Fix the issue
- [ ] Check other carousels

**Comment by demenech** [comment]
PR: #109
