### ISSUE TITLE
Show scrollbar for topics/orgs descriptions

### ISSUE THREAD

**Issue by demenech** [FCSCOpendata/frontend#116]
## Acceptance Criteria
- [ ] I can see a scrollbar for descriptions that are too long

## Tasks
- [ ] Add a scrollbar to the descriptions
- [ ] Make it appear only when hovered and when there's content being hidden
- [ ] Make sure it's minimalistic and themed according to the active topic
