### ISSUE TITLE
Handle Hierarchy sorting order for the topics

### ISSUE THREAD

**Issue by MuhammadIsmailShahzad** [FCSCOpendata/frontend#134]
We need to sort the topics hierarchy elements as requested by the client (Its not a bug). 

## Description

Currently we are getting alphabetically ordered group names but that considers `10` as `1` and `0` thus sorting `Group no 10:` before `Group no 1:` (similarly for others too as shown in the image below). 

This is not a bug but the default behaviour of CKAN. We looked into solving this in CKAN backend but personalizing sort according to this specific topic may interfere this with the rest of the group hierarchies and may get a bit tricky. Thus we decided this to handle this in the frontend while displaying the groups. 

![image](https://user-images.githubusercontent.com/57398621/203553220-361eef25-af8b-4fe1-9c23-a2c501322211.png)

## Acceptance

* [ ] Topic titles are shown in ascending order while considering the group number as `number` instead of seperate strings

## Tasks

* [ ] Analyse and perform fix
* [ ] Raise it to PM if any blockers or feasibility issues are there

**Comment by demenech** [comment]
PR: https://github.com/FCSCOpendata/frontend/pull/135

**Comment by demenech** [comment]
@MuhammadIsmailShahzad can we close this one?
