### ISSUE TITLE
Responsive Web Design

### ISSUE THREAD

**Issue by demenech** [FCSCOpendata/frontend#139]
When I navigate through the website, I want all pages to be responsive so that I can access and use it on all devices. 

##  Acceptance Criteria

- [ ] All the pages are usable on mobile
- [ ] All the pages are usable on tablet

## Tasks

- [x] Review and fix responsiveness issues on:
  - [x] **Global Sections and Components**
      - [x] Header Main Menu : Prevent menu from overriding other components on desktop
      - [x] Language Buttons: prevent line break
      - [x] Next Stop Section: prevent line break
      - [x] Footer
      - [x] Close menu after click on mobile
      - [x] Language overlap logo
  - [x] **Home**
      - [x] Form Search: Centralized on Tablet
      - [x] What's New Section: Break Columns on
          - [x] Tablet
          - [x] Mobile
  - [x] **Datasets**
      - [x] Dataset Item Card
          - [x] Tablet
          - [x] Mobile
  - [x] **Dataset Detail Page**
      - [x] Breadcrumb
      - [x] Title on small devices
      - [x] Dataset info
      - [x] Share, Cite, Rate
      - [x] Resources fixed height on small devices
      - [x] Resource preview and schema
  - [x] Build Your Data 
  - [x] **Organizations**
      - [x] Organization Item Card
          - [x] Tablet
          - [x] Mobile
      - [x] Topics items container 4k
      - [x] Developers Guide container 4k
  - [x] **Topics**
      - [x] Topic Item Card
         - [x] Tablet 
         - [x] Mobile 
  - [x] **101**
      - [x] Content horizontal padding
  - [x] **News**
      - [x] Article card
          - [x] Tablet 
          - [x] Mobile 
  - [x] **Applications**
      - [x] Content horizontal padding
      - [x] Grid
  - [x] **Real time data**
      - [x] Column break on tablet and mobile
      - [x] Small images on smaller devices
  - [x] **Request Data**
      - [x] Content horizontal padding
      - [x] Remove form margin on smaller devices
