### ISSUE TITLE
Accessibility fixes

### ISSUE THREAD

**Issue by demenech** [FCSCOpendata/frontend#140]
When I access the website, I want all pages to be accessible so that I can use the website regardless of any hearing or sight impairment. 

##  Acceptance Criteria

- [ ] All the pages meet the WCAG 2.2 level requirements
- [ ] All the pages are usable with text-to-speech extensions
- [ ] All the pages are usable with the keyboard

## Tasks

- [ ] Review and fix accessibility issues on:
  - [ ] ...
  - [ ] ...
