### ISSUE TITLE
Change the hover effect on topics list in the home page 

### ISSUE THREAD

**Issue by demenech** [FCSCOpendata/frontend#29]
## Acceptance Criteria
- [ ] I can see the carousels are using the old style
- [ ] It's present in the home page
- [ ] It's present in the topics page
- [ ] It's present in the orgs page

## Tasks
- [x] Revert to the old design i.e. the text is written in white, then when you hover, it has the current effect BUT inside the display, NOT outside
- [x] Do the same for subtopics
- [x] Do the same for suborgs

**Comment by demenech** [comment]
PR: #34
