### ISSUE TITLE
Update the topics/organizations caroussel

### ISSUE THREAD

**Issue by demenech** [FCSCOpendata/frontend#30]
## Acceptance Criteria
- [ ] I can  see the carrousels are updated

## Tasks
- [x] For the topics, everything should be visible in one view (show only the 10 primary topics)
- [x] Same for orgs, but keep the other orgs on the caroussel
- [x] Remove the preview of the half of the next item
- [x] When hovering the orgs, it should display arrows that indicate to the user there are more orgs. This behavior is gonna happen to topics as well when there's more than 10

**Comment by demenech** [comment]
PR: #35
