### ISSUE TITLE
Scrollbar Indicator - Display current org/topic icon as origin

### ISSUE THREAD

**Issue by demenech** [FCSCOpendata/frontend#31]
## Acceptance Criteria
- [ ] When I visit the topics page, the active topic icon is displayed as the origin in the scroll indicator
- [ ] When I visit the orgs page, the active org icon is displayed as the origin in the scroll indicator

## Tasks
- [ ] The scroll indicator should be dynamic in the topics and orgs pages, making it's origin display the icon of the current active item in the page
