### ISSUE TITLE
Small UI fixes

### ISSUE THREAD

**Issue by demenech** [FCSCOpendata/frontend#52]
## Acceptance Criteria
- [x] The search input at the home page looks more conspicuous
- [x] I can see the topics/org icons 30% bigger
- [ ] I can see everything is now using the correct font
- [x] I can see the photos have rounded edges (mainly on news and datasets list)
- [ ]  ~~I can see the format icon for the resource in /@ministry-education/schools-in-general-education~~
- [x] I can see each topic stylized according to it's accent color

## Tasks
- [x] The border of the search input on the homepage header should be like the outline that appears when the input is focused
- [x] Topics/Orgs Page - Increase the icon for topics/org by 30%
- [x] Have everything in Avenir Font
- [x] Photos should have rounded edges
- [x] ~~Fix broken image that's appearing in some datasets e.g. /@ministry-education/schools-in-general-education~~ (looking at the resource it looks like they just have to reupload the file)
     - [ ] ~~Discuss the icon to be used with team~~ 
- [x] Update the color code for the topic icon (same for the topic header)

**Comment by demenech** [comment]
PR: #53

**Comment by demenech** [comment]
Current icon being used for resources with unknown format
![ss-2022-08-30-15:45:25](https://user-images.githubusercontent.com/16550934/187517998-b74924ec-2646-46a5-ad77-b94092f4e0b5.png)

**Comment by demenech** [comment]
# Topic Color 
## Preview:
![ss-2022-08-30-18:51:21](https://user-images.githubusercontent.com/16550934/187550141-91153f26-6c69-4c92-a0ac-1aae7e5718eb.png)
  
**How it works?**
It grabs the color codes from `public/configs/topics.json`:
```{
    "topics": [
        {
            "name": "economy",
            "color": "#f8ad3b"
        },
        {
            "name": "food-security",
            "color": "#b7b71c" 
        },
        {
            "name": "education",
            "color": "#be272d" 
        },
        {
            "name": "environment",
            "color": "#39b24a" 
        },
        {
            "name": "social",
            "color": "#29a8df" 
        },
        {
            "name": "health-care",
            "color": "#00a69a" 
        },
        {
            "name": "sport",
            "color": "#0071b9" 
        },
        {
            "name": "government",
            "color": "#a88a62" 
        },
        {
            "name": "technology",
            "color": "#90278c" 
        },
        {
            "name": "transport",
            "color": "#d1145a" 
        },
        {
            "name": "infrastructure",
            "color": "#ee5a24" 
        }
    ]
} 
```

**What happens if the topic doesn't have a color setting?**
The default color is the green we were using previously.

## Please note: I didn't style the pill yet because as I was reviewing the presentation I noticed it was not mentioned, and also II think it would not be good to use the same color for a background, but it's open for discussion.

**Comment by osahon-okungbowa** [comment]
@demenech Regarding this task - "Photos should have rounded edges"

This should also cover images in certain carousels and sections e.g.
- [ ] carousel for filtering topic and organisations
- [ ] carousel for sub-topics and sub organisations
- [ ] images under each section of "Explore Similar Datasets"

**Comment by demenech** [comment]
PR: #57
