### ISSUE TITLE
support Arabic CMS Content (including content pulled from the CMS for Header and Footer Labels)

### ISSUE THREAD

**Issue by osahon-okungbowa** [FCSCOpendata/frontend#55]
when i visit the Arabic version of the portal, i want the content being pulled from the CMS to be available in Arabic as well, so the Arabic speaking visitors can use the portal

## Tasks
- [x] Make Header Menu is available in Arabic from the CMS
- [x] Make Footer Menu Item is available in Arabic from the CMS
- [x] Make List of News articles (when visiting the news link) only contains Arabic news articles from the CMS
- [x] Make Each News article from the news list above is displayed in Arabic

#### Tips That might help complete tasks
- Ghost provides tags. there are 2 categories (internal tags & public tags): internal tags can be used to group collection of pages or post and is not displayed to the public. We need to check if there is a way to filter posts by tags when querying for news articles. If so, maybe we can ask the client to tag all arabic posts with `#ar` to indicate arabic post
- We can also agree that all post/pages link starting with `ar-` after the base URL should be considered an Arabic page

NOTE: these are just ideas from a quick investigation. please do your own investigation for the best solutions when necessary

**Comment by demenech** [comment]
## NOTES:
For the news:
- I decided to distinguish the lang of the news using a tag. All you have to do is create a tag with name `#arabic` and slug `ar` and add it (or not) to the posts.
- Also added this lang filter to the `Next reads` section .
For the static pages:
- When navigating with the locale set as Arabic, the data is gonna be fetched from `ar-*slug*`. Otherwise it's `*slug*`. E.g.: if you go to the page /terms-of-use in English, it's gonna look for the page with the URI `/terms-of-use`, now, if you do it in Arabic, it's gonna look for the page with the URI `/ar-terms-of-use`. Note that `*slug*` in this example is `terms-of-use`.

**Comment by demenech** [comment]
## Navbar/Footer Links:
All you have to do is create a new entry in navigation settings and make the last component of the URL follow this format:
`/ar-*path*`
Where *path* is the English equivalent of the desired link.
E.g.:
If we want to create a translation for the nav item `Open Data 101` we should have an English link that points to `/open-data-101`, then create another entry with the desired translation (e.g.: `Open Data 101 in Arabic`) and finally make sure that this last entry points to `/ar-open-data-101`

![image](https://user-images.githubusercontent.com/16550934/188214448-96b9b24b-fe0e-4a1a-b2af-c36919e13481.png)
