### ISSUE TITLE
Add navigation arrows to all carousels

### ISSUE THREAD

**Issue by demenech** [FCSCOpendata/frontend#69]
## Acceptance criteria
- [x] Search page
    - [x] I can see nav arrows on the topics carousel
    - [x] I can see nav arrows on the subtopics carousel
    - [x] I can see nav arrows on the organizations carousel

## Tasks
- [x] Add scroll indicators for all carousels of the search filter on the Dataset page. Scroll indicator should work exactly like topics/org navbar.
