### ISSUE TITLE
Ability to dynamically update Hero images on Home page from the CMS

### ISSUE THREAD

**Issue by demenech** [FCSCOpendata/frontend#81]
## Acceptance Criteria
- [x] I can change the 4 images that are shown on the hero section on the home page.

## Tasks
- [x] Extract the background image (pattern + dashed line) from the mocks
- [x] Add it as the new background image
- [x] Extract the images in the 4 tiles to use it as a default
- [x] Reconstruct the background image with CSS
- [x] Make it editable from GhostCMS
- [x] Make sure it works for Arabic too
