### ISSUE TITLE
2022-09-08 - UI Issues Reported by the client

### ISSUE THREAD

**Issue by demenech** [FCSCOpendata/frontend#89]
## Tasks
- [x] Reverse the scroll indicator dynamic icon position.
- [x] Increase the size of the topic icons in the navbar
- [x] The topic color code for the navbar should shown only when the topic is selected for display. The default color should be used when not selected
- [x] icon in the description of the Topic/Org page needs to maintain the same position regardless of length of Topic/Org Title . the icon should vertically align to the top.
