### ISSUE TITLE
Topics/Orgs Page image section size

### ISSUE THREAD

**Issue by demenech** [FCSCOpendata/frontend#91]
## Acceptance Criteria
- [x] I can see that the alignment between the topic image section and the description section is always uniform
- [ ] I can see that the alignment between the org image section and the description section is always uniform

## Tasks
- [x] Make the image sections on the topics and orgs pages have standardized sizes

**Comment by demenech** [comment]
PR: #94
