### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by steveoni** [FCSCOpendata/frontend#92]
We want to add a contact page for users to send in complaints, suggestions, or issues

## Acceptance

- [x] contact UI provided
- [x] Able to send email

## Task

- [x] create contact UI (contact page and form)
- [x] create api to send email
