### ISSUE TITLE
Add Contact and Request Form links to navbar/footer

### ISSUE THREAD

**Issue by demenech** [FCSCOpendata/frontend#96]
## Acceptance Criteria
- [ ] Contact and Request Datasets is present on the default navbar/footer links list

## Tasks
- [x] We wanna make sure Contact and Request Datasets links are present on the default links list for the navbar and the footer
    - [x] Navbar should have the contact link
    - [x] Footer should have both
