### ISSUE TITLE
2022-09-13 - Minor issues

### ISSUE THREAD

**Issue by demenech** [FCSCOpendata/frontend#99]
## Tasks
- [x] The “Open Data 101” component still redirects to the English version when we are in Arabic
- [x] Fix padding issues in Arabic for the Explore Similar Datasets” tabs
- [x] For the Frontend ReadMe, review/update the section for [i18n translation](https://github.com/FCSCOpendata/frontend#i18n-configuration)
- [x] Reenable SSR for dataset page
- [x] When in Arabic, the news on the homepage are making the language switch back to English
- [x] Add vertical margin between the tags in the home page
